name: oauth2_manager
description: A Dart package for authentication management for all systems
version: 1.0.0
repository: https://github.com/Abbas1Hussein/oauth2_manager

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  oauth2: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
